import { enableProdMode } from '@angular/core';
import { platformBrowser } from '@angular/platform-browser';

/*
* Instead of importing AppModule, import AppModuleNgFactory, which is
* the compiled application generated by the Angular compiler.
*/
import { AppModuleNgFactory } from './app/app.module.ngfactory';

/* 
* Disables Angular's development mode, turning off assertions & other checks 
* within the framework.
*/
enableProdMode();

/* 
* Import platformBrowser & not platformBrowserDynamic, because in AOT compilation, 
* the app is shipped to the browser already compiled, whereas in JIT compilation, the
* compilation is done at the browser level. 
*/
platformBrowser().bootstrapModuleFactory(AppModuleNgFactory);